# Generated by Django 5.1.7 on 2025-03-19 11:41

from django.db import migrations, models
# migrations → Handles database changes.

# models → Provides field types to define database structure


# Defines a migration class that Django will use to modify the database.
class Migration(migrations.Migration):

    initial = True
    # This means it's the first migration for this model.

    # It creates the FitnessPlan table from scratch.

    dependencies = [
    ]
    # Since it's the first migration, it has no previous migrations to depend on.

    operations = [
        migrations.CreateModel(
            name='FitnessPlan',
            fields=[  
                # Creates a new database table named FitnessPlan, the fields list contains all the columns in the table.
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('fitness_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20)),
                ('goal', models.CharField(help_text='E.g., Weight Loss, Muscle Gain, Endurance', max_length=255)),
                ('duration_weeks', models.IntegerField(help_text='Duration in weeks')),
                ('workout_schedule', models.TextField(help_text='Describe weekly workout plan')),
            ],
        ),
    ]
