# Generated by Django 5.1.7 on 2025-03-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('fitness_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20)),
                ('goal', models.CharField(help_text='E.g., Weight Loss, Muscle Gain, Endurance', max_length=255)),
                ('duration_weeks', models.IntegerField(help_text='Duration in weeks')),
                ('workout_schedule', models.TextField(help_text='Describe weekly workout plan')),
            ],
        ),
    ]
